### ISSUE TITLE
Security server installation meta-package for Faroe Islands

### ISSUE THREAD

**Issue by jhyoty** [TalgilduFO/X-Road#1]
New security server installation meta-package (`xroad-securityserver-fo`) with customized default configuration for Ubuntu 18.04 and RHEL 7 and 8.

The installation package should include the following customized configuration in `override-securityserver-fo.ini` to make the authentication and signing keys generated by security server 3072 bits. 

Addition: pin complexity rules should be enforced

```
[signer]
key-length=3072
enforce-token-pin-policy=true
```

**Comment by martensoo** [comment]
Token PIN currently not enforced (as default)
Currently EE and FI packages are mentioned in the installation documentation while IS is not. Should FO be mentioned?

PR:
https://github.com/TalgilduFO/X-Road/pull/3

**Comment by jhyoty** [comment]
Let's leave updating the documentation out of the scope for now. We probably need to raise this issue in NIIS (I'm not sure if the country-specific meta-packages should be in the generic "vanilla" documentation).

Maybe we should check with @AndrasEliassen about the security server token PIN policy.

**Comment by AndrasEliassen** [comment]
Yes, let's set the complexity requirements as you suggested, @jhyoty:
"software token pin is required to be at least 10 ASCII characters from at least tree character classes (lowercase letters, uppercase letters, digits, special characters)"

**Comment by martensoo** [comment]
Token PIN policy enforced
